Vagrant.configure(2) do |config|
  config.vm.define "node01" do |node| # Management Server
    node.vm.network "private_network", ip: "192.168.15.1"
    node.vm.hostname = "node01"
    node.vm.box = "ubuntu/vivid64"
    node.vm.provision "shell", inline: <<-SHELL
	sudo -s
	cd /etc/apt/sources.list.d/
	curl http://www.beegfs.com/release/beegfs_2015.03/dists/beegfs-deb8.list > /etc/apt/sources.list.d/beegfs-deb8.list
	curl http://www.beegfs.com/release/beegfs_2015.03/gpg/DEB-GPG-KEY-beegfs | apt-key add -
	apt-get update

	apt-get install -yq beegfs-mgmtd 

	echo 192.168.15.1 node01 >> /etc/hosts
	echo 192.168.15.2 node02 >> /etc/hosts
	echo 192.168.15.3 node03 >> /etc/hosts
	echo 192.168.15.4 node04 >> /etc/hosts
	echo 192.168.15.5 node05 >> /etc/hosts
     
  SHELL

  end

  config.vm.define "node02" do |node| # Metadata Server
    node.vm.network "private_network", ip: "192.168.15.2"
    node.vm.hostname = "node02"
    node.vm.box = "ubuntu/vivid64"
    node.vm.provision "shell", inline: <<-SHELL
	sudo -s
	cd /etc/apt/sources.list.d/
	curl http://www.beegfs.com/release/beegfs_2015.03/dists/beegfs-deb8.list > /etc/apt/sources.list.d/beegfs-deb8.list
	curl http://www.beegfs.com/release/beegfs_2015.03/gpg/DEB-GPG-KEY-beegfs | apt-key add -
	apt-get update

	apt-get install -yq beegfs-meta 

	echo 192.168.15.1 node01 >> /etc/hosts
	echo 192.168.15.2 node02 >> /etc/hosts
	echo 192.168.15.3 node03 >> /etc/hosts
	echo 192.168.15.4 node04 >> /etc/hosts
	echo 192.168.15.5 node05 >> /etc/hosts

     
  SHELL

  end

  config.vm.define "node03" do |node| # Storage Server
    node.vm.network "private_network", ip: "192.168.15.3"
    node.vm.hostname = "node03"
    node.vm.box = "ubuntu/vivid64"
    node.vm.provision "shell", inline: <<-SHELL
	sudo -s
	cd /etc/apt/sources.list.d/
	curl http://www.beegfs.com/release/beegfs_2015.03/dists/beegfs-deb8.list > /etc/apt/sources.list.d/beegfs-deb8.list
	curl http://www.beegfs.com/release/beegfs_2015.03/gpg/DEB-GPG-KEY-beegfs | apt-key add -
	apt-get update

	apt-get install -yq beegfs-storage

 	echo 192.168.15.1 node01 >> /etc/hosts
	echo 192.168.15.2 node02 >> /etc/hosts
	echo 192.168.15.3 node03 >> /etc/hosts
	echo 192.168.15.4 node04 >> /etc/hosts
	echo 192.168.15.5 node05 >> /etc/hosts
    
  SHELL

  end

  config.vm.define "node04" do |node| # Client
    node.vm.network "private_network", ip: "192.168.15.4"
    node.vm.hostname = "node04"
    node.vm.box = "ubuntu/vivid64"
    node.vm.provision "shell", inline: <<-SHELL
	sudo -s
	cd /etc/apt/sources.list.d/
	curl http://www.beegfs.com/release/beegfs_2015.03/dists/beegfs-deb8.list > /etc/apt/sources.list.d/beegfs-deb8.list
	curl http://www.beegfs.com/release/beegfs_2015.03/gpg/DEB-GPG-KEY-beegfs | apt-key add -
	apt-get update

	apt-get install -yq beegfs-client beegfs-helperd beegfs-utils

	echo 192.168.15.1 node01 >> /etc/hosts
	echo 192.168.15.2 node02 >> /etc/hosts
	echo 192.168.15.3 node03 >> /etc/hosts
	echo 192.168.15.4 node04 >> /etc/hosts
	echo 192.168.15.5 node05 >> /etc/hosts
     
  SHELL

  end

  config.vm.define "node05" do |node| # Admon Server (optional for graphical interface)
    node.vm.network "private_network", ip: "192.168.15.5"
    node.vm.hostname = "node05"
    node.vm.box = "ubuntu/vivid64"
    node.vm.provision "shell", inline: <<-SHELL
	sudo -s
	cd /etc/apt/sources.list.d/
	curl http://www.beegfs.com/release/beegfs_2015.03/dists/beegfs-deb8.list > /etc/apt/sources.list.d/beegfs-deb8.list
	curl http://www.beegfs.com/release/beegfs_2015.03/gpg/DEB-GPG-KEY-beegfs | apt-key add -
	apt-get update

	apt-get install -yq beegfs-admon

	echo 192.168.15.1 node01 >> /etc/hosts
	echo 192.168.15.2 node02 >> /etc/hosts
	echo 192.168.15.3 node03 >> /etc/hosts
	echo 192.168.15.4 node04 >> /etc/hosts
	echo 192.168.15.5 node05 >> /etc/hosts
     
  SHELL

  end

end
