Vagrant.configure(2) do |config|

  config.vm.define "node01" do |node| # Management Server
    node.vm.box = "ubuntu/vivid64"
    node.vm.provision "shell", inline: <<-SHELL
	sudo -s
	cd /etc/apt/sources.list.d/
	curl http://www.beegfs.com/release/beegfs_2015.03/dists/beegfs-deb8.list > /etc/apt/sources.list.d/beegfs-deb8.list
	curl http://www.beegfs.com/release/beegfs_2015.03/gpg/DEB-GPG-KEY-beegfs | apt-key add -
	apt-get update

	apt-get install -yq beegfs-mgmtd 
     
  SHELL

  end

  config.vm.define "node02" do |node| # Metadata Server
    node.vm.box = "ubuntu/vivid64"
    node.vm.provision "shell", inline: <<-SHELL
	sudo -s
	cd /etc/apt/sources.list.d/
	curl http://www.beegfs.com/release/beegfs_2015.03/dists/beegfs-deb8.list > /etc/apt/sources.list.d/beegfs-deb8.list
	curl http://www.beegfs.com/release/beegfs_2015.03/gpg/DEB-GPG-KEY-beegfs | apt-key add -
	apt-get update

	apt-get install -yq beegfs-meta 
     
  SHELL

  end

  config.vm.define "node02" do |node| # Storage Server
    node.vm.box = "ubuntu/vivid64"
    node.vm.provision "shell", inline: <<-SHELL
	sudo -s
	cd /etc/apt/sources.list.d/
	curl http://www.beegfs.com/release/beegfs_2015.03/dists/beegfs-deb8.list > /etc/apt/sources.list.d/beegfs-deb8.list
	curl http://www.beegfs.com/release/beegfs_2015.03/gpg/DEB-GPG-KEY-beegfs | apt-key add -
	apt-get update

	apt-get install -yq beegfs-storage
     
  SHELL

  end

  config.vm.define "node04" do |node| # Client
    node.vm.box = "ubuntu/vivid64"
    node.vm.provision "shell", inline: <<-SHELL
	sudo -s
	cd /etc/apt/sources.list.d/
	curl http://www.beegfs.com/release/beegfs_2015.03/dists/beegfs-deb8.list > /etc/apt/sources.list.d/beegfs-deb8.list
	curl http://www.beegfs.com/release/beegfs_2015.03/gpg/DEB-GPG-KEY-beegfs | apt-key add -
	apt-get update

	apt-get install -yq beegfs-client beegfs-helperd beegfs-utils
     
  SHELL

  end

  config.vm.define "node05" do |node| # Admon Server (optional for graphical interface)
    node.vm.box = "ubuntu/vivid64"
    node.vm.provision "shell", inline: <<-SHELL
	sudo -s
	cd /etc/apt/sources.list.d/
	curl http://www.beegfs.com/release/beegfs_2015.03/dists/beegfs-deb8.list > /etc/apt/sources.list.d/beegfs-deb8.list
	curl http://www.beegfs.com/release/beegfs_2015.03/gpg/DEB-GPG-KEY-beegfs | apt-key add -
	apt-get update

	apt-get install -yq beegfs-admon
     
  SHELL

  end

end
