---
- hosts: all
  become: yes
  tasks:

    - name : Ceph repo
      apt_repository: repo='deb http://download.ceph.com/debian-firefly/ wheezy main' state=present

    - name: caph apt keys
      apt_key: url=https://download.ceph.com/keys/release.asc state=present

    - name: nptd
      apt: pkg=ntp state=latest
      notify:
      - restart ntpd

    - lineinfile: dest=/etc/hosts line='192.168.15.11 node01' owner=root group=root mode=0644
    - lineinfile: dest=/etc/hosts line='192.168.15.12 node02' owner=root group=root mode=0644
    - lineinfile: dest=/etc/hosts line='192.168.15.13 node03' owner=root group=root mode=0644
    - lineinfile: dest=/etc/hosts line='192.168.15.14 node04' owner=root group=root mode=0644

    - copy: src=ceph.com.pem dest=/etc/ssl/certs/ceph.com owner=root group=root mode=0644
