Vagrant.configure(2) do |config|
  config.vm.box = "debian/wheezy64"
  config.vm.provision "ansible" do |ansible|
    	ansible.playbook = "ceph-playbook.yml"
  end

  config.vm.define "node01" do |node| # Management Server
    node.vm.network "private_network", ip: "192.168.15.11"
    node.vm.hostname = "node01"
  end
  config.vm.define "node02" do |node| # Management Server
    node.vm.network "private_network", ip: "192.168.15.12"
    node.vm.hostname = "node02"
    node.vm.provision "ansible" do |ansible|
    	ansible.playbook = "ceph-playbook.yml"
    end
  end
  config.vm.define "node03" do |node| # Management Server
    node.vm.network "private_network", ip: "192.168.15.13"
    node.vm.hostname = "node03"
    node.vm.provision "ansible" do |ansible|
    	ansible.playbook = "ceph-playbook.yml"
    end
  end
 config.vm.define "node04" do |node| # Management Server
    node.vm.network "private_network", ip: "192.168.15.14"
    node.vm.hostname = "node04"
    node.vm.provision "ansible" do |ansible|
    	ansible.playbook = "ceph-playbook.yml"
    end
  end
end
