Vagrant.configure(2) do |config|
  config.vm.define "node01" do |node| # Management Server
    node.vm.network "private_network", ip: "192.168.15.1"
    node.vm.box = "ubuntu/vivid64"
    node.vm.hostname = "node01"
    node.vm.provision "ansible" do |ansible|
    	ansible.playbook = "ceph-playbook.yml"
    end
#    node.vm.provision "shell", inline: <<-SHELL
#	sudo -s
#	apt-get install wget
#	wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -
#	echo deb http://download.ceph.com/debian-{ceph-stable-release}/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list
#	apt-get update
#	apt-get update && apt-get install ceph-deploy
#	apt-get install ntp
#
#	useradd -d /home/ceph -m ceph
#	passwd ceph ceph
#
#	echo "ceph ALL = (root) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/{username}
#	chmod 0440 /etc/sudoers.d/ceph
#
#	[ -a /home/ceph/.ssh/id_rsa ] ssh-keygen -P ""  -f /home/ceph/.ssh/id_rsa 
#
#	echo 192.168.15.1 node01 >> /etc/hosts
#	echo 192.168.15.2 node02 >> /etc/hosts
#	echo 192.168.15.3 node03 >> /etc/hosts
#	echo 192.168.15.4 node04 >> /etc/hosts
#	echo 192.168.15.5 node05 >> /etc/hosts
#     
#  SHELL

  end

end
