---
- hosts: all
  become: yes
  tasks:

    - lineinfile: dest=/etc/hosts line='192.168.15.11 node01' owner=root group=root mode=0644
    - lineinfile: dest=/etc/hosts line='192.168.15.12 node02' owner=root group=root mode=0644
    - lineinfile: dest=/etc/hosts line='192.168.15.13 node03' owner=root group=root mode=0644
    - lineinfile: dest=/etc/hosts line='192.168.15.14 node04' owner=root group=root mode=0644

    - apt_key: url=http://ppa.moosefs.com/stable/apt/moosefs.key state=present

    - apt_repository: repo='deb http://ppa.moosefs.com/stable/apt/debian/wheezy wheezy main' state=present
