# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # config.vm.box = "hansode/fedora-21-server-x86_64"
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.ssh.forward_agent = true

  config.vm.define "serv1" do |serv1|
    serv1.vm.box = "hansode/fedora-21-server-x86_64"
    serv1.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "128"]
    end
  end

  config.vm.define "serv2" do |serv2|
    serv2.vm.box = "hansode/fedora-21-server-x86_64"
    serv2.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "128"]
    end
  end

  config.vm.define "serv3" do |serv3|
    serv3.vm.box = "hansode/fedora-21-server-x86_64"
    serv3.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "128"]
    end
  end





end
